import React from "react";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../assets/css/globals.css";
import "../assets/css/tailwind/custom.css";

const geistMono = Poppins({
  variable: "--ff-poppins",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Marvin Villamar - Full Stack Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="hydrated">
      <body className={`${geistMono.variable} antialiased`}>{children}</body>
    </html>
  );
}
